[2024-09-20T22:58:35.032+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-20T22:58:35.107+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Read_data_and_move_data.Read_dataset_files scheduled__2024-09-20T22:40:00+00:00 [queued]>
[2024-09-20T22:58:35.131+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Read_data_and_move_data.Read_dataset_files scheduled__2024-09-20T22:40:00+00:00 [queued]>
[2024-09-20T22:58:35.134+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-20T22:58:35.178+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): Read_dataset_files> on 2024-09-20 22:40:00+00:00
[2024-09-20T22:58:35.226+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'Read_data_and_move_data', 'Read_dataset_files', 'scheduled__2024-09-20T22:40:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion.py', '--cfg-path', '/tmp/tmpa_kv87c2']
[2024-09-20T22:58:35.246+0000] {standard_task_runner.py:105} INFO - Job 69: Subtask Read_dataset_files
[2024-09-20T22:58:35.247+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=58) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-20T22:58:35.251+0000] {standard_task_runner.py:72} INFO - Started process 70 to run task
[2024-09-20T22:58:35.500+0000] {task_command.py:467} INFO - Running <TaskInstance: Read_data_and_move_data.Read_dataset_files scheduled__2024-09-20T22:40:00+00:00 [running]> on host 90c3f75c79c3
[2024-09-20T22:58:35.721+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='Read_data_and_move_data' AIRFLOW_CTX_TASK_ID='Read_dataset_files' AIRFLOW_CTX_EXECUTION_DATE='2024-09-20T22:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-09-20T22:40:00+00:00'
[2024-09-20T22:58:35.728+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-09-20T22:58:35.729+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-09-20T22:58:35.732+0000] {logging_mixin.py:190} INFO - Current task name:Read_dataset_files state:running start_date:2024-09-20 22:58:35.109281+00:00
[2024-09-20T22:58:35.733+0000] {logging_mixin.py:190} INFO - Dag name:Read_data_and_move_data and current dag run status:running
[2024-09-20T22:58:35.735+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-20T22:58:35.742+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion.py", line 14, in read_data
    raise ValueError("No files in the folder")
ValueError: No files in the folder
[2024-09-20T22:58:35.808+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2024-09-20T22:58:35.810+0000] {logging_mixin.py:190} INFO - Task start:2024-09-20 22:58:35.109281+00:00 end:2024-09-20 22:58:35.807476+00:00 duration:0.698195
[2024-09-20T22:58:35.811+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): Read_dataset_files> dag:<DAG: Read_data_and_move_data> dagrun:<DagRun Read_data_and_move_data @ 2024-09-20 22:40:00+00:00: scheduled__2024-09-20T22:40:00+00:00, state:running, queued_at: 2024-09-20 22:57:58.931871+00:00. externally triggered: False>
[2024-09-20T22:58:35.812+0000] {logging_mixin.py:190} INFO - Failure caused by No files in the folder
[2024-09-20T22:58:35.814+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=Read_data_and_move_data, task_id=Read_dataset_files, run_id=scheduled__2024-09-20T22:40:00+00:00, execution_date=20240920T224000, start_date=20240920T225835, end_date=20240920T225835
[2024-09-20T22:58:35.860+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-20T22:58:35.862+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 69 for task Read_dataset_files (No files in the folder; 70)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/data_ingestion.py", line 14, in read_data
    raise ValueError("No files in the folder")
ValueError: No files in the folder
[2024-09-20T22:58:36.081+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-09-20T22:58:36.240+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-20T22:58:36.247+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
